baseURL = "https://khaiverse.github.io/kweb/"
languageCode = "en-us"
title = "Khaiverse"
contentDir = "content"
paginate = 2 #Luek list sik tempo lek bale

[taxonomies]
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "Sitemap"]
